# gen_version.ps1 - 生成 version.h，包含固件版本和 Git 信息
param(
    [string]$VersionFile = "version.txt",
    [string]$OutputHeader = "User/version.h",
    [string]$ProjectRoot = ""
)

if (-not $ProjectRoot) {
    $ProjectRoot = Split-Path -Parent $PSCommandPath
    $ProjectRoot = Split-Path -Parent $ProjectRoot
}
Set-Location $ProjectRoot

# 读取版本号
$version = Get-Content $VersionFile -Raw
$version = $version.Trim()
$parts = $version -split '\.'
$major = if ($parts[0]) { $parts[0] } else { "0" }
$minor = if ($parts[1]) { $parts[1] } else { "0" }
$build = if ($parts[2]) { $parts[2] } else { "0" }

# Git 信息
$gitHash = ""
$gitBranch = ""
$gitDirty = ""
$gitCommitCount = "0"

try {
    $gitHash = git rev-parse --short=7 HEAD 2>$null
    $gitBranch = git rev-parse --abbrev-ref HEAD 2>$null
    $gitCommitCount = git rev-list --count HEAD 2>$null
    
    # 检查是否有未提交的修改
    $status = git status --porcelain 2>$null
    if ($status) {
        $gitDirty = "-dirty"
    }
} catch {
    # 不在 Git 仓库中，使用默认值
}

$buildDate = Get-Date -Format "yyyy-MM-dd"
$buildTime = Get-Date -Format "HH:mm:ss"

$versionFull = "Ver ${major}.${minor}.${build}"

# 生成 version.h
$header = @"
/*
 * version.h - Auto-generated by tools/gen_version.ps1, DO NOT EDIT manually.
 * Generated: ${buildDate} ${buildTime}
 */

#ifndef VERSION_H_
#define VERSION_H_

#define VERSION_MAJOR       ${major}
#define VERSION_MINOR       ${minor}
#define VERSION_BUILD       ${build}
#define VERSION_STRING      "${versionFull}"
#define GIT_HASH            "${gitHash}${gitDirty}"
#define GIT_BRANCH          "${gitBranch}"
#define GIT_COMMIT_COUNT    "${gitCommitCount}"
#define BUILD_DATE          "${buildDate}"
#define BUILD_TIME          "${buildTime}"

/* Version string for display (clean, no git info) */
#define VERSION             "${versionFull}"

/* Full version string with git info (for debugging) */
#define VERSION_FULL        "${versionFull} (${gitHash}${gitDirty})"

#endif /* VERSION_H_ */
"@

$outputPath = Join-Path $ProjectRoot $OutputHeader
$existing = $null
if (Test-Path $outputPath) {
    $existing = Get-Content $outputPath -Raw
}

if ($existing -ne $header) {
    Set-Content -Path $outputPath -Value $header -Encoding ASCII
    Write-Host "version.h generated: ${versionFull} (${gitHash}${gitDirty})"
} else {
    Write-Host "version.h unchanged: ${versionFull} (${gitHash}${gitDirty})"
}
