/*
 * version.h - Auto-generated by tools/gen_version.ps1, DO NOT EDIT manually.
 * Generated: 2026-06-17 23:10:25
 */

#ifndef VERSION_H_
#define VERSION_H_

#define VERSION_MAJOR       1
#define VERSION_MINOR       2
#define VERSION_BUILD       4
#define VERSION_STRING      "Ver 1.2.4"
#define GIT_HASH            "99c62e1-dirty"
#define GIT_BRANCH          "main"
#define GIT_COMMIT_COUNT    "35"
#define BUILD_DATE          "2026-06-17"
#define BUILD_TIME          "23:10:25"

/* Version string for display (clean, no git info) */
#define VERSION             "Ver 1.2.4"

/* Full version string with git info (for debugging) */
#define VERSION_FULL        "Ver 1.2.4 (99c62e1-dirty)"

#endif /* VERSION_H_ */
