/*
 * version.h - Auto-generated by tools/gen_version.ps1, DO NOT EDIT manually.
 * Generated: 2026-06-08 21:19:30
 */

#ifndef VERSION_H_
#define VERSION_H_

#define VERSION_MAJOR       1
#define VERSION_MINOR       1
#define VERSION_BUILD       8
#define VERSION_STRING      "Ver 1.1.8"
#define GIT_HASH            "7acefde-dirty"
#define GIT_BRANCH          "main"
#define GIT_COMMIT_COUNT    "28"
#define BUILD_DATE          "2026-06-08"
#define BUILD_TIME          "21:19:30"

/* Version string for display (clean, no git info) */
#define VERSION             "Ver 1.1.8"

/* Full version string with git info (for debugging) */
#define VERSION_FULL        "Ver 1.1.8 (7acefde-dirty)"

#endif /* VERSION_H_ */
