/*
 * version.h - Auto-generated by tools/gen_version.ps1, DO NOT EDIT manually.
 * Generated: 2026-06-07 14:03:20
 */

#ifndef VERSION_H_
#define VERSION_H_

#define VERSION_MAJOR       1
#define VERSION_MINOR       1
#define VERSION_BUILD       6
#define VERSION_STRING      "Ver 1.1.6"
#define GIT_HASH            "9685059-dirty"
#define GIT_BRANCH          "main"
#define GIT_COMMIT_COUNT    "25"
#define BUILD_DATE          "2026-06-07"
#define BUILD_TIME          "14:03:20"

/* Version string for display (clean, no git info) */
#define VERSION             "Ver 1.1.6"

/* Full version string with git info (for debugging) */
#define VERSION_FULL        "Ver 1.1.6 (9685059-dirty)"

#endif /* VERSION_H_ */
